# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev


pool:
  name: Azure Pipelines

resources:
- repo: self


variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: SonarQubePrepare@7
      inputs:
        SonarQube: 'my-sonarqube-ado'
        scannerMode: 'cli'
        configMode: 'manual'
        cliProjectKey: 'Evershop-ecommerce_Evershop-ecommerce_AZMfTF-C5yvYUCCqjDCZ'
        cliSources: '.'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
